import { Alert, Button, ButtonBase, Container, IconButton, InputBase, Snackbar, Typography } from "@mui/material";
import LightModeIcon from "@mui/icons-material/LightMode";
import DarkModeIcon from "@mui/icons-material/DarkMode";
import Head from "next/head";
import { useState } from "react";
import useThemeStore from "../store/themeStore";
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const currentTheme = useThemeStore((state) => state.currentTheme);
  const toggleTheme = useThemeStore((state) => state.toggleTheme);

  const [open, setOpen] = useState(false)
   const handleClick = () => {
     setOpen(true);
   };

   const handleClose = (event, reason) => {
     if (reason === "clickaway") {
       return;
     }

     setOpen(false);
   };


   

  const handleThemeBtnClick = () => {
    toggleTheme();
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="xl" sx={{ marginTop: "30px" }}>
        <Typography variant="h1" gutterBottom>
          h1. Heading
        </Typography>
        <Button
          color="primary"
          variant="contained"
          disableElevation
          onClick={handleClick}
          sx={{ marginRight: "10px" }}
        >
          Submit
        </Button>

        <IconButton aria-label="theme toggler" onClick={handleThemeBtnClick}>
          {currentTheme === "light" && <DarkModeIcon sx={{color: "text.primary" }}/>}

          {currentTheme === "dark" && (
            <LightModeIcon style={{ color: "orange" }} />
          )}
        </IconButton>

        <Snackbar
          open={open}
          autoHideDuration={6000}
          onClose={handleClose}
          anchorOrigin={{ vertical: "top", horizontal: "right" }}
        >
          <Alert severity="success" onClose={handleClose}>
            This is a success alert — check it out!
          </Alert>
        </Snackbar>
      </Container>
    </>
  );
}
